title: My Website 
description: >- # this means to ignore newlines until "baseurl"
  Research and posts by Linh Cao.
url: https://emlcao.github.io 
author:
  name: Linh Cao
  url: https://github.com/emlcao

# Build settings
theme: minima
remote_theme: jekyll/minima
